export const fibLangZhCN = {
  name: '名称',
  save: '保存',
  saveAs: '另存为',
  back: '返回',
  loading: '加载中...',
  resetOperations: '重置/删除所有操作',
  changesLoseWarningHint: '如果按下“重置”按钮，您的更改将会丢失。是否继续？',
  discardChangesWarningHint: '如果关闭弹窗，您最近的更改将不会被保存。',
  cancel: '取消',
  apply: '应用',
  warning: '警告',
  confirm: '确认',
  discardChanges: '放弃更改',
  undoTitle: '撤销上一步操作',
  redoTitle: '重做上一步操作',
  showImageTitle: '显示原始图像',
  zoomInTitle: '放大',
  zoomOutTitle: '缩小',
  toggleZoomMenuTitle: '切换缩放菜单',
  adjustTab: '调整',
  finetuneTab: '精细调节',
  filtersTab: '滤镜',
  watermarkTab: '水印',
  annotateTabLabel: '注释',
  resize: '调整大小',
  resizeTab: '调整大小',
  imageName: '图像名称',
  invalidImageError: '提供的图像无效。',
  uploadImageError: '上传图像时出错。',
  areNotImages: '不是图像',
  isNotImage: '不是图像',
  toBeUploaded: '待上传',
  cropTool: '裁剪',
  original: '原始',
  custom: '自定义',
  square: '正方形',
  landscape: '横向',
  portrait: '纵向',
  ellipse: '椭圆',
  classicTv: '经典电视',
  cinemascope: '宽银幕',
  arrowTool: '箭头',
  blurTool: '模糊',
  brightnessTool: '亮度',
  contrastTool: '对比度',
  ellipseTool: '椭圆',
  unFlipX: '取消水平翻转',
  flipX: '水平翻转',
  unFlipY: '取消垂直翻转',
  flipY: '垂直翻转',
  hsvTool: 'HSV',
  hue: '色调',
  brightness: '亮度',
  saturation: '饱和度',
  value: '明度',
  imageTool: '图像',
  importing: '正在导入...',
  addImage: '+ 添加图像',
  uploadImage: '上传图像',
  fromGallery: '从图库',
  lineTool: '直线',
  penTool: '画笔',
  polygonTool: '多边形',
  sides: '边数',
  rectangleTool: '矩形',
  cornerRadius: '圆角半径',
  resizeWidthTitle: '宽度（像素）',
  resizeHeightTitle: '高度（像素）',
  toggleRatioLockTitle: '切换宽高比锁定',
  resetSize: '恢复为原始图像尺寸',
  rotateTool: '旋转',
  textTool: '文本',
  textSpacings: '文字间距',
  textAlignment: '文字对齐',
  fontFamily: '字体',
  size: '大小',
  letterSpacing: '字间距',
  lineHeight: '行高',
  warmthTool: '色温',
  addWatermark: '+ 添加水印',
  addTextWatermark: '+ 添加文字水印',
  addWatermarkTitle: '选择水印类型',
  uploadWatermark: '上传水印',
  addWatermarkAsText: '作为文本添加',
  padding: '内边距',
  paddings: '内边距',
  shadow: '阴影',
  horizontal: '水平',
  vertical: '垂直',
  blur: '模糊',
  opacity: '不透明度',
  transparency: '透明度',
  position: '位置',
  stroke: '描边',
  saveAsModalTitle: '另存为',
  extension: '扩展名',
  format: '格式',
  nameIsRequired: '名称是必填项。',
  quality: '质量',
  imageDimensionsHoverTitle: '保存的图像尺寸（宽 x 高）',
  cropSizeLowerThanResizedWarning: '注意，所选裁剪区域小于已应用的调整大小，可能导致质量下降',
  actualSize: '实际大小 (100%)',
  fitSize: '适应尺寸',
  addImageTitle: '选择要添加的图像...',
  mutualizedFailedToLoadImg: '加载图像失败。',
  tabsMenu: '菜单',
  download: '下载',
  width: '宽度',
  height: '高度',
  plus: '+',
  cropItemNoEffect: '此裁剪项目无预览可用',
};

export const tuiLang = {
  "3:2": "3:2",
  "4:3": "4:3",
  "5:4": "5:4",
  "7:5": "7:5",
  "16:9": "16:9",
  Apply: "应用",
  Arrow: "箭头",
  "Arrow-2": "箭头-2",
  "Arrow-3": "箭头-3",
  Blend: "混合",
  Blur: "模糊",
  Bold: "粗体",
  Brightness: "亮度",
  Bubble: "气泡",
  Cancel: "取消",
  Center: "居中",
  Circle: "圆形",
  Color: "颜色",
  "Color Filter": "颜色滤镜",
  Crop: "裁剪",
  Custom: "自定义",
  "Custom icon": "自定义图标",
  Delete: "删除",
  "Delete-all": "全部删除",
  Distance: "距离",
  Download: "下载",
  Draw: "绘制",
  Emboss: "浮雕",
  Fill: "填充",
  Filter: "滤镜",
  Flip: "翻转",
  "Flip X": "水平翻转",
  "Flip Y": "垂直翻转",
  Free: "自由",
  Grayscale: "灰度",
  Heart: "心形",
  Icon: "图标",
  Invert: "反色",
  Italic: "斜体",
  Left: "左对齐",
  Load: "加载",
  "Load Mask Image": "加载遮罩图像",
  Location: "位置",
  Mask: "遮罩",
  Multiply: "正片叠底",
  Noise: "噪点",
  Pixelate: "像素化",
  Polygon: "多边形",
  Range: "范围",
  Rectangle: "矩形",
  Redo: "重做",
  "Remove White": "移除白色",
  Reset: "重置",
  Right: "右对齐",
  Rotate: "旋转",
  Sepia: "褐色调",
  Sepia2: "褐色调2",
  Shape: "形状",
  Sharpen: "锐化",
  Square: "正方形",
  "Star-1": "星形-1",
  "Star-2": "星形-2",
  Straight: "直线",
  Stroke: "描边",
  Text: "文本",
  "Text size": "文本大小",
  Threshold: "阈值",
  Tint: "色调",
  Triangle: "三角形",
  Underline: "下划线",
  Undo: "撤销",
  Value: "值"
}

export const tuiLight = {
  'common.bi.image': 'https://uicdn.toast.com/toastui/img/tui-image-editor-bi.png',
  'common.bisize.width': '251px',
  'common.bisize.height': '21px',
  'common.backgroundImage': './img/bg.png',
  'common.backgroundColor': '#fff',
  'common.border': '1px solid #c1c1c1',


  // header
  'header.backgroundImage': 'none',
  'header.backgroundColor': 'transparent',
  'header.border': '0px',

  // load button
  'loadButton.backgroundColor': '#fff',
  'loadButton.border': '1px solid #ddd',
  'loadButton.color': '#222',
  'loadButton.fontFamily': "'Noto Sans', sans-serif",
  'loadButton.fontSize': '12px',

  // download button
  'downloadButton.backgroundColor': '#fdba3b',
  'downloadButton.border': '1px solid #fdba3b',
  'downloadButton.color': '#fff',
  'downloadButton.fontFamily': "'Noto Sans', sans-serif",
  'downloadButton.fontSize': '12px',

  // main icons
  'menu.normalIcon.color': '#8a8a8a',
  'menu.activeIcon.color': '#555555',
  'menu.disabledIcon.color': '#434343',
  'menu.hoverIcon.color': '#e9e9e9',
  'menu.iconSize.width': '24px',
  'menu.iconSize.height': '24px',

  // submenu icons
  'submenu.normalIcon.color': '#8a8a8a',
  'submenu.activeIcon.color': '#555555',
  'submenu.iconSize.width': '32px',
  'submenu.iconSize.height': '32px',

  // submenu primary color
  'submenu.backgroundColor': 'transparent',
  'submenu.partition.color': '#e5e5e5',

  // submenu labels
  'submenu.normalLabel.color': '#858585',
  'submenu.normalLabel.fontWeight': 'normal',
  'submenu.activeLabel.color': '#000',
  'submenu.activeLabel.fontWeight': 'normal',

  // checkbox style
  'checkbox.border': '1px solid #ccc',
  'checkbox.backgroundColor': '#fff',

  // rango style
  'range.pointer.color': '#333',
  'range.bar.color': '#ccc',
  'range.subbar.color': '#606060',

  'range.disabledPointer.color': '#d3d3d3',
  'range.disabledBar.color': 'rgba(85,85,85,0.06)',
  'range.disabledSubbar.color': 'rgba(51,51,51,0.2)',

  'range.value.color': '#000',
  'range.value.fontWeight': 'normal',
  'range.value.fontSize': '11px',
  'range.value.border': '0',
  'range.value.backgroundColor': '#f5f5f5',
  'range.title.color': '#000',
  'range.title.fontWeight': 'lighter',

  // colorpicker style
  'colorpicker.button.border': '0px',
  'colorpicker.title.color': '#000',
}
export const tuiDark = {
  'common.bi.image': 'https://uicdn.toast.com/toastui/img/tui-image-editor-bi.png',
  'common.bisize.width': '251px',
  'common.bisize.height': '21px',
  'common.backgroundImage': 'none',
  'common.backgroundColor': '#1e1e1e',
  'common.border': '0px',

  // header
  'header.backgroundImage': 'none',
  'header.backgroundColor': 'transparent',
  'header.border': '0px',

  // load button
  'loadButton.backgroundColor': '#fff',
  'loadButton.border': '1px solid #ddd',
  'loadButton.color': '#222',
  'loadButton.fontFamily': "'Noto Sans', sans-serif",
  'loadButton.fontSize': '12px',

  // download button
  'downloadButton.backgroundColor': '#fdba3b',
  'downloadButton.border': '1px solid #fdba3b',
  'downloadButton.color': '#fff',
  'downloadButton.fontFamily': "'Noto Sans', sans-serif",
  'downloadButton.fontSize': '12px',

  // main icons
  'menu.normalIcon.color': '#8a8a8a',
  'menu.activeIcon.color': '#555555',
  'menu.disabledIcon.color': '#434343',
  'menu.hoverIcon.color': '#e9e9e9',
  'menu.iconSize.width': '24px',
  'menu.iconSize.height': '24px',

  // submenu icons
  'submenu.normalIcon.color': '#8a8a8a',
  'submenu.activeIcon.color': '#e9e9e9',
  'submenu.iconSize.width': '32px',
  'submenu.iconSize.height': '32px',

  // submenu primary color
  'submenu.backgroundColor': '#1e1e1e',
  'submenu.partition.color': '#3c3c3c',

  // submenu labels
  'submenu.normalLabel.color': '#8a8a8a',
  'submenu.normalLabel.fontWeight': 'lighter',
  'submenu.activeLabel.color': '#fff',
  'submenu.activeLabel.fontWeight': 'lighter',

  // checkbox style
  'checkbox.border': '0px',
  'checkbox.backgroundColor': '#fff',

  // range style
  'range.pointer.color': '#fff',
  'range.bar.color': '#666',
  'range.subbar.color': '#d1d1d1',

  'range.disabledPointer.color': '#414141',
  'range.disabledBar.color': '#282828',
  'range.disabledSubbar.color': '#414141',

  'range.value.color': '#fff',
  'range.value.fontWeight': 'lighter',
  'range.value.fontSize': '11px',
  'range.value.border': '1px solid #353535',
  'range.value.backgroundColor': '#151515',
  'range.title.color': '#fff',
  'range.title.fontWeight': 'lighter',

  // colorpicker style
  'colorpicker.button.border': '1px solid #1e1e1e',
  'colorpicker.title.color': '#fff',

}

export const filerbotDarkTheme = {
  'txt-primary': '#FFFFFF',
  'txt-secondary': '#CCCCCC',
  'txt-secondary-invert': '#333333',
  'txt-placeholder': '#888888',
  'txt-warning': '#FFCC00',
  'txt-error': '#FF4C4C',
  'txt-info': '#66CCFF',

  'accent-primary': '#00BFFF',
  'accent-primary-hover': '#33CCFF',
  'accent-primary-active': '#0099CC',
  'accent-primary-disabled': '#555555',
  'accent-secondary-disabled': '#444444',
  'accent-stateless': '#00BFFF',
  'accent-stateless_0_4_opacity': 'rgba(0, 191, 255, 0.4)',
  'accent_0_5_5_opacity': 'rgba(0, 191, 255, 0.55)',
  'accent_0_5_opacity': 'rgba(0, 191, 255, 0.5)',
  'accent_0_7_opacity': 'rgba(0, 191, 255, 0.7)',
  'accent_1_2_opacity': 'rgba(0, 191, 255, 1)',
  'accent_1_8_opacity': 'rgba(0, 191, 255, 1)',
  'accent_2_8_opacity': 'rgba(0, 191, 255, 1)',
  'accent_4_0_opacity': 'rgba(0, 191, 255, 1)',

  'bg-grey': '#2A2A2A',
  'bg-stateless': '#1E1E1E',
  'bg-active': '#333333',
  'bg-base-light': '#2C2C2C',
  'bg-base-medium': '#1A1A1A',
  'bg-primary': '#121212',
  'bg-primary-light': '#1F1F1F',
  'bg-primary-hover': '#2A2A2A',
  'bg-primary-active': '#3A3A3A',
  'bg-primary-stateless': '#121212',
  'bg-primary-0-5-opacity': 'rgba(18, 18, 18, 0.5)',
  'bg-secondary': '#1A1A1A',
  'bg-hover': '#2E2E2E',
  'bg-green': '#1F3D1F',
  'bg-green-medium': '#2F5F2F',
  'bg-blue': '#1F2F3D',
  'bg-red': '#3D1F1F',
  'bg-red-light': '#5F2F2F',
  'background-red-medium': '#7F3F3F',
  'bg-orange': '#4F2F1F',
  'bg-tooltip': '#333333',

  'icon-primary': '#FFFFFF',
  'icons-primary-opacity-0-6': 'rgba(255, 255, 255, 0.6)',
  'icons-secondary': '#AAAAAA',
  'icons-placeholder': '#777777',
  'icons-invert': '#000000',
  'icons-muted': '#555555',
  'icons-primary-hover': '#DDDDDD',
  'icons-secondary-hover': '#BBBBBB',

  'btn-primary-text': '#FFFFFF',
  'btn-primary-text-0-6': 'rgba(255, 255, 255, 0.6)',
  'btn-primary-text-0-4': 'rgba(255, 255, 255, 0.4)',
  'btn-disabled-text': '#666666',
  'btn-secondary-text': '#CCCCCC',

  'link-primary': '#00BFFF',
  'link-stateless': '#00BFFF',
  'link-hover': '#33CCFF',
  'link-active': '#0099CC',
  'link-muted': '#888888',
  'link-pressed': '#006699',

  'borders-primary': '#444444',
  'borders-primary-hover': '#666666',
  'borders-secondary': '#333333',
  'borders-strong': '#888888',
  'borders-invert': '#FFFFFF',
  'border-hover-bottom': '#00BFFF',
  'border-active-bottom': '#0099CC',
  'border-primary-stateless': '#444444',
  'borders-disabled': '#555555',
  'borders-button': '#666666',
  'borders-item': '#444444',
  'borders-base-light': '#2C2C2C',
  'borders-base-medium': '#1A1A1A',
  'borders-green': '#2F5F2F',
  'borders-green-medium': '#3F7F3F',
  'borders-red': '#7F3F3F',

  // 其他状态色、阴影、渐变等也可以继续补充
  'active-secondary': '#2E2E2E',
  'active-secondary-hover': '#3A3A3A',

  'tag': '#444444',
  'states-error-disabled-text': '#993333',

  'error': '#FF4C4C',
  'error-0-28-opacity': 'rgba(255, 76, 76, 0.28)',
  'error-0-12-opacity': 'rgba(255, 76, 76, 0.12)',
  'error-hover': '#FF6666',
  'error-active': '#CC3333',

  'success': '#4CAF50',
  'success-hover': '#66BB6A',
  'success-Active': '#388E3C',

  'warning': '#FFCC00',
  'warning-hover': '#FFDD33',
  'warning-active': '#FFB300',

  'info': '#66CCFF',
  'modified': '#FF99CC',

  'red': '#FF4C4C',
  'orange': '#FF9900',
  'salad': '#A8D5BA',
  'green': '#4CAF50',
  'blue': '#2196F3',
  'indigo': '#3F51B5',
  'violet': '#9C27B0',
  'pink': '#E91E63',

  'gradient-right': 'linear-gradient(to right, #1E1E1E, #2A2A2A)',
  'gradient-right-active': 'linear-gradient(to right, #2A2A2A, #3A3A3A)',
  'gradient-right-hover': 'linear-gradient(to right, #2A2A2A, #4A4A4A)',

  'extra-0-3-overlay': 'rgba(0, 0, 0, 0.3)',
  'extra-0-5-overlay': 'rgba(0, 0, 0, 0.5)',
  'extra-0-7-overlay': 'rgba(0, 0, 0, 0.7)',
  'extra-0-9-overlay': 'rgba(0, 0, 0, 0.9)',

  'red-0-1-overlay': 'rgba(255, 76, 76, 0.1)',
  'orange-0-1-overlay': 'rgba(255, 153, 0, 0.1)',
  'accent-0-8-overlay': 'rgba(0, 191, 255, 0.8)',
  'green-0-2-Overlay': 'rgba(76, 175, 80, 0.2)',
  'white-0-7-8-overlay': 'rgba(255, 255, 255, 0.78)',

  'link': '#00BFFF',
  'camera': '#FFFFFF',
  'google-drive': '#FFFFFF',
  'dropbox': '#FFFFFF',
  'one-drive': '#FFFFFF',
  'device': '#FFFFFF',
  'instagram': '#FFFFFF',
  'free-images': '#FFFFFF',
  'free-icons': '#FFFFFF',
  'canvas': '#FFFFFF',
  'box': '#FFFFFF',
  'screen-cast': '#FFFFFF',
  'unsplash': '#FFFFFF',

  'light-shadow': '0px 1px 3px rgba(0, 0, 0, 0.2)',
  'medium-shadow': '0px 3px 6px rgba(0, 0, 0, 0.3)',
  'large-shadow': '0px 10px 20px rgba(0, 0, 0, 0.4)',
  'x-large-shadow': '0px 15px 30px rgba(0, 0, 0, 0.5)',
};
